-- Migración 06 — banco de preguntas CAE (48 ítems auto-corregibles)
-- Reading & Use of English, formato original. Requiere migration_04 (tabla).
INSERT INTO exam_questions (part, level, prompt, options, answer, given_word, explanation) VALUES
  ('mc_cloze','C1','The committee eventually reached a ____ decision after hours of heated debate.','["unanimous","united","universal","uniform"]','unanimous',NULL,'"Unanimous decision" significa que todos estan de acuerdo; las otras opciones no colocan con "decision" en este sentido.'),
  ('mc_cloze','C1','The generous host ____ no expense in organising the anniversary celebration.','["spared","saved","kept","withheld"]','spared',NULL,'"Spare no expense" es la expresion fija que significa no escatimar en gastos.'),
  ('mc_cloze','C1','The fresh evidence ____ serious doubt on his version of events.','["cast","threw","put","laid"]','cast',NULL,'La colocacion correcta es "cast doubt on" (sembrar dudas sobre algo).'),
  ('mc_cloze','C1','His vague reply was completely wide of the ____.','["mark","point","target","aim"]','mark',NULL,'"Wide of the mark" es un modismo que significa muy equivocado o desacertado.'),
  ('mc_cloze','C1','It took her years to come to ____ with the collapse of the family business.','["terms","grips","ends","odds"]','terms',NULL,'"Come to terms with" significa aceptar o asumir algo dificil.'),
  ('mc_cloze','C1','The incoming director quickly ____ a fresh approach to the failing project.','["adopted","adapted","adhered","admitted"]','adopted',NULL,'"Adopt an approach" es la colocacion correcta; "adapt" significa modificar, no elegir.'),
  ('mc_cloze','C1','Under no ____ should you disclose these figures to the press.','["circumstances","conditions","situations","occasions"]','circumstances',NULL,'"Under no circumstances" es la estructura enfatica fija que exige inversion.'),
  ('mc_cloze','C1','The adaptation bears little ____ to the novel it was supposedly based on.','["resemblance","similarity","likeness","comparison"]','resemblance',NULL,'"Bear a resemblance to" es la colocacion natural para expresar parecido.'),
  ('mc_cloze','C1','Her closing argument was so ____ that nobody in the room could refute it.','["compelling","compulsory","compulsive","competing"]','compelling',NULL,'"Compelling" significa convincente; las demas opciones tienen significados distintos.'),
  ('mc_cloze','C1','The two accounts of the accident are fundamentally at ____ with each other.','["odds","ends","terms","stake"]','odds',NULL,'"At odds with" significa en desacuerdo o en contradiccion con algo.'),
  ('mc_cloze','C1','The authorities have vowed to ____ down on online fraud this year.','["crack","break","cut","turn"]','crack',NULL,'"Crack down on" es el phrasal verb que significa tomar medidas severas contra algo.'),
  ('mc_cloze','C1','A sudden power cut brought the entire production line to an abrupt ____.','["halt","stop","end","close"]','halt',NULL,'"Bring something to a halt" es la colocacion fija para detener algo de golpe.'),
  ('open_cloze','C1','No sooner ____ she arrived at the office than the fire alarm went off.',NULL,'had',NULL,'"No sooner had + sujeto + participio" es una estructura de inversion enfatica.'),
  ('open_cloze','C1','It was not until well after midnight ____ the last guests finally left.',NULL,'that',NULL,'La estructura enfatica "not until ... that" requiere "that" para introducir la clausula.'),
  ('open_cloze','C1','She stubbornly insisted ____ paying for the entire meal herself.',NULL,'on',NULL,'El verbo "insist" va seguido de la preposicion "on" y gerundio.'),
  ('open_cloze','C1','The harder he practised, ____ more confident he became on stage.',NULL,'the',NULL,'La estructura comparativa doble usa "the ...-er, the more ...".'),
  ('open_cloze','C1','Little ____ they realise that a huge surprise was waiting for them at home.',NULL,'did',NULL,'"Little did they realise" es una inversion enfatica con auxiliar en pasado.'),
  ('open_cloze','C1','I would rather you ____ not mention any of this to your colleagues.',NULL,'did',NULL,'"Would rather you did not" expresa preferencia sobre la conducta de otra persona.'),
  ('open_cloze','C1','By the time the ambulance arrived, the patient ____ already regained consciousness.',NULL,'had',NULL,'El pasado perfecto "had regained" indica accion anterior a otra accion pasada.'),
  ('open_cloze','C1','He apologised sincerely ____ having kept the whole team waiting for an hour.',NULL,'for',NULL,'"Apologise for + -ing" es la estructura correcta para disculparse por algo hecho.'),
  ('open_cloze','C1','Such ____ her enthusiasm that the entire audience felt genuinely inspired.',NULL,'was',NULL,'"Such was + sustantivo" es una inversion enfatica que antepone el complemento.'),
  ('open_cloze','C1','The whole department is really looking forward ____ meeting the new intern.',NULL,'to',NULL,'"Look forward to" siempre va seguido de gerundio; "to" es preposicion aqui.'),
  ('open_cloze','C1','Not only ____ he forget his passport, but he also missed the connecting flight.',NULL,'did',NULL,'"Not only did + sujeto + infinitivo" es la inversion tras un adverbio negativo inicial.'),
  ('open_cloze','C1','____ for your timely warning, we would certainly have taken the wrong turning.',NULL,'But',NULL,'"But for" equivale a "if it had not been for" e introduce una condicion hipotetica.'),
  ('word_formation','C1','The young scientist made a ground-breaking ____ about the origins of the galaxy. (DISCOVER)',NULL,'discovery','DISCOVER','El sustantivo derivado de "discover" es "discovery".'),
  ('word_formation','C1','His utterly ____ behaviour during the crisis shocked the entire board. (RESPONSIBLE)',NULL,'irresponsible','RESPONSIBLE','El adjetivo negativo se forma con el prefijo "ir-": "irresponsible".'),
  ('word_formation','C1','There has been a marked ____ in air quality since the old plant shut down. (IMPROVE)',NULL,'improvement','IMPROVE','El sustantivo de "improve" es "improvement".'),
  ('word_formation','C1','The assembly instructions were so ____ that nobody managed to follow them. (CONFUSE)',NULL,'confusing','CONFUSE','El adjetivo con sentido activo (que provoca confusion) es "confusing".'),
  ('word_formation','C1','She argued ____ for a complete overhaul of the outdated system. (PASSION)',NULL,'passionately','PASSION','El adverbio derivado de "passion" es "passionately".'),
  ('word_formation','C1','The painstaking ____ of the medieval manuscript took almost a decade. (RESTORE)',NULL,'restoration','RESTORE','El sustantivo de "restore" es "restoration".'),
  ('word_formation','C1','Her flat ____ to compromise ultimately cost her the promotion. (REFUSE)',NULL,'refusal','REFUSE','El sustantivo de "refuse" es "refusal".'),
  ('word_formation','C1','The revised strategy proved remarkably ____ in cutting down on waste. (EFFECT)',NULL,'effective','EFFECT','El adjetivo derivado de "effect" es "effective".'),
  ('word_formation','C1','They chose to settle in a remote and largely ____ stretch of coastline. (POPULATE)',NULL,'unpopulated','POPULATE','El adjetivo negativo se forma con "un-" y el participio: "unpopulated".'),
  ('word_formation','C1','The seminar gave the students a far deeper ____ of the underlying issue. (UNDERSTAND)',NULL,'understanding','UNDERSTAND','El sustantivo de "understand" es "understanding".'),
  ('word_formation','C1','Her initial ____ of the risks turned out to be remarkably accurate. (ASSESS)',NULL,'assessment','ASSESS','El sustantivo de "assess" es "assessment".'),
  ('word_formation','C1','The volunteers worked ____ throughout the night to meet the tight deadline. (TIRE)',NULL,'tirelessly','TIRE','El adverbio con sentido de "sin cansarse" es "tirelessly".'),
  ('key_word_transformation','C1','"It''s possible that she forgot about the appointment." || She ____ about the appointment. [HAVE]',NULL,'may have forgotten','HAVE','"May/might have + participio" expresa posibilidad en el pasado.'),
  ('key_word_transformation','C1','"I haven''t eaten proper sushi for five years." || The last ____ proper sushi was five years ago. [TIME]',NULL,'time I ate','TIME','"The last time I + pasado simple" reformula un periodo desde la ultima vez.'),
  ('key_word_transformation','C1','"People say that he is a brilliant surgeon." || He ____ a brilliant surgeon. [SAID]',NULL,'is said to be','SAID','La pasiva impersonal "is said to be" reformula "people say that".'),
  ('key_word_transformation','C1','"They will probably cancel the outdoor concert." || The outdoor concert ____ cancelled. [LIKELY]',NULL,'is likely to be','LIKELY','"Is likely to be" expresa probabilidad de forma equivalente a "will probably".'),
  ('key_word_transformation','C1','"I regret not booking the tickets earlier." || I wish ____ the tickets earlier. [BOOKED]',NULL,'I had booked','BOOKED','"Wish + pasado perfecto" expresa arrepentimiento por algo no hecho.'),
  ('key_word_transformation','C1','"You didn''t need to bring any food." || It ____ for you to bring any food. [NECESSARY]',NULL,'was not necessary','NECESSARY','"It was not necessary for you to" reformula la ausencia de obligacion.'),
  ('key_word_transformation','C1','"Someone should have warned us about the storm." || We ____ about the storm. [WARNED]',NULL,'should have been warned','WARNED','La pasiva "should have been + participio" traslada la critica al sujeto afectado.'),
  ('key_word_transformation','C1','"She only understood the joke after everyone had left." || Not until everyone had left ____ the joke. [DID]',NULL,'did she understand','DID','Tras "not until" al inicio se produce inversion: "did + sujeto + infinitivo".'),
  ('key_word_transformation','C1','"I find it hard to concentrate when it is noisy." || I have ____ when it is noisy. [DIFFICULTY]',NULL,'difficulty in concentrating','DIFFICULTY','"Have difficulty (in) + -ing" expresa dificultad para hacer algo.'),
  ('key_word_transformation','C1','"He was too exhausted to finish the marathon." || He was ____ he couldn''t finish the marathon. [SO]',NULL,'so exhausted that','SO','"So + adjetivo + that" reformula "too + adjetivo + to".'),
  ('key_word_transformation','C1','"Despite the heavy rain, they enjoyed the picnic." || Even ____ raining heavily, they enjoyed the picnic. [WAS]',NULL,'though it was','WAS','"Even though it was" introduce una concesion equivalente a "despite".'),
  ('key_word_transformation','C1','"It was a mistake to leave the back door unlocked." || I ____ the back door unlocked. [HAVE]',NULL,'should not have left','HAVE','"Should not have + participio" expresa critica de una accion pasada equivocada.')
;

SELECT part, COUNT(*) FROM exam_questions GROUP BY part ORDER BY part;
