-- Migración 05 — banco de vocabulario CAE (120 palabras A2-C1)
-- Contenido original generado para la app; método SRS sobre estas palabras.
INSERT INTO words (word, translation, example_sentence, level, category) VALUES
  ('borrow', 'pedir prestado', 'Can I borrow your pen for a moment?', 'A2', 'general'),
  ('neighbour', 'vecino', 'Our new neighbour invited us over for coffee.', 'A2', 'general'),
  ('cheap', 'barato', 'This restaurant is really cheap but the food is great.', 'A2', 'general'),
  ('busy', 'ocupado', 'I am very busy at work this week.', 'A2', 'general'),
  ('improve', 'mejorar', 'She wants to improve her English before the trip.', 'A2', 'general'),
  ('weather', 'el tiempo (clima)', 'The weather was perfect for a walk in the park.', 'A2', 'general'),
  ('tidy up', 'ordenar', 'Please tidy up your room before dinner.', 'A2', 'phrasal'),
  ('get up', 'levantarse', 'I usually get up at seven every morning.', 'A2', 'phrasal'),
  ('wake up', 'despertarse', 'The loud noise made me wake up in the middle of the night.', 'A2', 'phrasal'),
  ('look after', 'cuidar', 'Could you look after my dog while I am away?', 'A2', 'phrasal'),
  ('try on', 'probarse (ropa)', 'You should try on those shoes before buying them.', 'A2', 'phrasal'),
  ('put on', 'ponerse (ropa)', 'Put on your coat, it is cold outside.', 'A2', 'phrasal'),
  ('healthy', 'sano', 'Eating fruit every day keeps you healthy.', 'A2', 'general'),
  ('expensive', 'caro', 'That car is too expensive for me right now.', 'A2', 'general'),
  ('crowded', 'abarrotado', 'The train was so crowded that we had to stand.', 'A2', 'general'),
  ('journey', 'viaje, trayecto', 'The journey to the coast takes about three hours.', 'A2', 'general'),
  ('comfortable', 'cómodo', 'These new chairs are very comfortable.', 'A2', 'general'),
  ('quiet', 'tranquilo, silencioso', 'We found a quiet café to study in.', 'A2', 'general'),
  ('hurry up', 'darse prisa', 'Hurry up or we will miss the bus.', 'A2', 'phrasal'),
  ('get on', 'subirse (a un transporte)', 'We got on the bus just before it left.', 'A2', 'phrasal'),
  ('achievement', 'logro', 'Finishing the marathon was a huge achievement for her.', 'B1', 'general'),
  ('advertisement', 'anuncio', 'I saw an advertisement for the job online.', 'B1', 'general'),
  ('deal with', 'lidiar con, tratar', 'Managers have to deal with difficult situations every day.', 'B1', 'phrasal'),
  ('find out', 'averiguar, descubrir', 'I need to find out what time the meeting starts.', 'B1', 'phrasal'),
  ('point out', 'señalar', 'She pointed out a mistake in my report.', 'B1', 'phrasal'),
  ('carry out', 'llevar a cabo', 'The team carried out a survey among local residents.', 'B1', 'phrasal'),
  ('set up', 'montar, establecer', 'They set up a small business last year.', 'B1', 'phrasal'),
  ('get along', 'llevarse bien', 'I get along well with most of my colleagues.', 'B1', 'phrasal'),
  ('run out of', 'quedarse sin', 'We ran out of milk this morning.', 'B1', 'phrasal'),
  ('take part in', 'participar en', 'Hundreds of students took part in the competition.', 'B1', 'phrasal'),
  ('environment', 'medio ambiente', 'Recycling helps protect the environment.', 'B1', 'general'),
  ('opportunity', 'oportunidad', 'This job is a great opportunity to learn new skills.', 'B1', 'general'),
  ('confident', 'seguro de sí mismo', 'She felt confident before the interview.', 'B1', 'general'),
  ('disappointed', 'decepcionado', 'He was disappointed with his exam results.', 'B1', 'general'),
  ('suggestion', 'sugerencia', 'Can I make a suggestion about the schedule?', 'B1', 'general'),
  ('persuade', 'persuadir, convencer', 'I managed to persuade my parents to let me travel alone.', 'B1', 'general'),
  ('avoid', 'evitar', 'Try to avoid using your phone late at night.', 'B1', 'general'),
  ('deadline', 'fecha límite', 'We must submit the project before the deadline.', 'B1', 'business'),
  ('colleague', 'colega, compañero', 'One of my colleagues is retiring next month.', 'B1', 'business'),
  ('customer', 'cliente', 'The shop always treats its customers with respect.', 'B1', 'business'),
  ('schedule', 'horario, agenda', 'My schedule is very tight on Mondays.', 'B1', 'business'),
  ('apply for', 'solicitar', 'She decided to apply for a scholarship.', 'B1', 'phrasal'),
  ('give back', 'devolver', 'Remember to give back the book you borrowed.', 'B1', 'phrasal'),
  ('figure out', 'resolver, entender', 'I cannot figure out how this machine works.', 'B1', 'phrasal'),
  ('once in a while', 'de vez en cuando', 'We eat out once in a while as a treat.', 'B1', 'idiom'),
  ('make up your mind', 'decidirse', 'You need to make up your mind about the holiday soon.', 'B1', 'idiom'),
  ('break the ice', 'romper el hielo', 'He told a joke to break the ice at the meeting.', 'B1', 'idiom'),
  ('research', 'investigación', 'She is doing research on renewable energy.', 'B1', 'academic'),
  ('summary', 'resumen', 'Please write a short summary of the article.', 'B1', 'academic'),
  ('topic', 'tema', 'Climate change was the main topic of the debate.', 'B1', 'academic'),
  ('take up', 'empezar (una afición), ocupar', 'He took up painting after he retired.', 'B2', 'phrasal'),
  ('put off', 'posponer, aplazar', 'They had to put off the wedding until next spring.', 'B2', 'phrasal'),
  ('come up with', 'idear, proponer', 'We need to come up with a better solution.', 'B2', 'phrasal'),
  ('look into', 'investigar', 'The company promised to look into the complaint.', 'B2', 'phrasal'),
  ('get by', 'arreglárselas', 'It is hard to get by on such a low salary.', 'B2', 'phrasal'),
  ('sort out', 'solucionar, arreglar', 'I need to sort out this problem before Friday.', 'B2', 'phrasal'),
  ('rely on', 'depender de, confiar en', 'You can rely on her to finish the task on time.', 'B2', 'phrasal'),
  ('stand out', 'destacar', 'Her creative ideas really made her stand out.', 'B2', 'phrasal'),
  ('take over', 'asumir el control, hacerse cargo', 'A larger firm took over the small company.', 'B2', 'phrasal'),
  ('hold on', 'esperar, aguantar', 'Hold on a second while I check the details.', 'B2', 'phrasal'),
  ('worthwhile', 'que vale la pena', 'The extra effort was definitely worthwhile.', 'B2', 'general'),
  ('overwhelming', 'abrumador', 'The response to the campaign was overwhelming.', 'B2', 'general'),
  ('straightforward', 'sencillo, directo', 'The instructions were clear and straightforward.', 'B2', 'general'),
  ('widespread', 'generalizado', 'There is widespread concern about rising prices.', 'B2', 'general'),
  ('hesitant', 'vacilante, indeciso', 'She was hesitant to share her opinion at first.', 'B2', 'general'),
  ('demanding', 'exigente', 'His new job is far more demanding than the last one.', 'B2', 'general'),
  ('rewarding', 'gratificante', 'Teaching can be a very rewarding career.', 'B2', 'general'),
  ('drawback', 'inconveniente, desventaja', 'The main drawback of the plan is its cost.', 'B2', 'general'),
  ('asset', 'ventaja, activo', 'Her language skills are a real asset to the team.', 'B2', 'business'),
  ('revenue', 'ingresos', 'The company''s revenue grew by ten percent.', 'B2', 'business'),
  ('stakeholder', 'parte interesada', 'All the stakeholders were invited to the meeting.', 'B2', 'business'),
  ('negotiate', 'negociar', 'They negotiated a better price for the equipment.', 'B2', 'business'),
  ('productivity', 'productividad', 'Flexible hours can boost employee productivity.', 'B2', 'business'),
  ('hypothesis', 'hipótesis', 'The experiment was designed to test the hypothesis.', 'B2', 'academic'),
  ('significant', 'significativo, importante', 'There was a significant increase in sales.', 'B2', 'academic'),
  ('evidence', 'evidencia, pruebas', 'There is strong evidence to support this theory.', 'B2', 'academic'),
  ('conclusion', 'conclusión', 'The report ends with a clear conclusion.', 'B2', 'academic'),
  ('approach', 'enfoque', 'We need a fresh approach to this old problem.', 'B2', 'academic'),
  ('on the other hand', 'por otro lado', 'It is cheaper; on the other hand, the quality is lower.', 'B2', 'idiom'),
  ('get cold feet', 'acobardarse, echarse atrás', 'He got cold feet just before signing the contract.', 'B2', 'idiom'),
  ('hit the nail on the head', 'dar en el clavo', 'You hit the nail on the head with that comment.', 'B2', 'idiom'),
  ('cost an arm and a leg', 'costar un ojo de la cara', 'The repairs cost an arm and a leg.', 'B2', 'idiom'),
  ('once and for all', 'de una vez por todas', 'Let us settle this argument once and for all.', 'B2', 'idiom'),
  ('keep an eye on', 'vigilar, estar atento a', 'Could you keep an eye on my bag for a minute?', 'B2', 'idiom'),
  ('under the weather', 'indispuesto, pachucho', 'I am feeling a bit under the weather today.', 'B2', 'idiom'),
  ('put up with', 'aguantar, tolerar', 'I cannot put up with this noise any longer.', 'C1', 'phrasal'),
  ('account for', 'explicar, representar', 'These costs account for most of the budget.', 'C1', 'phrasal'),
  ('rule out', 'descartar', 'The police have not ruled out any suspects yet.', 'C1', 'phrasal'),
  ('wear off', 'desvanecerse (un efecto)', 'The effect of the medicine will wear off after a few hours.', 'C1', 'phrasal'),
  ('iron out', 'resolver (detalles)', 'We still need to iron out a few details before launch.', 'C1', 'phrasal'),
  ('brush up on', 'repasar, refrescar', 'I should brush up on my French before the conference.', 'C1', 'phrasal'),
  ('water down', 'suavizar, diluir', 'The final proposal was watered down to please everyone.', 'C1', 'phrasal'),
  ('bank on', 'contar con, confiar en', 'Do not bank on the weather staying fine all week.', 'C1', 'phrasal'),
  ('wind up', 'acabar (de cierta manera)', 'If you keep spending, you will wind up in debt.', 'C1', 'phrasal'),
  ('gloss over', 'pasar por alto, restar importancia', 'The report glossed over the most serious issues.', 'C1', 'phrasal'),
  ('cumbersome', 'engorroso', 'The old software was slow and cumbersome to use.', 'C1', 'general'),
  ('inevitable', 'inevitable', 'With so little preparation, failure seemed inevitable.', 'C1', 'general'),
  ('profound', 'profundo', 'The book had a profound impact on my thinking.', 'C1', 'general'),
  ('ambiguous', 'ambiguo', 'The wording of the contract was rather ambiguous.', 'C1', 'general'),
  ('arbitrary', 'arbitrario', 'The decision felt completely arbitrary and unfair.', 'C1', 'general'),
  ('scrutinise', 'examinar minuciosamente', 'Auditors will scrutinise every transaction in detail.', 'C1', 'general'),
  ('tentative', 'provisional, tentativo', 'We have reached a tentative agreement for now.', 'C1', 'general'),
  ('plausible', 'plausible, verosímil', 'That sounds like a plausible explanation to me.', 'C1', 'general'),
  ('conducive', 'propicio', 'A quiet room is more conducive to studying.', 'C1', 'general'),
  ('streamline', 'optimizar, agilizar', 'The new system will streamline the entire process.', 'C1', 'business'),
  ('leverage', 'aprovechar, apalancar', 'The firm hopes to leverage its brand to enter new markets.', 'C1', 'business'),
  ('downsize', 'reducir plantilla', 'The company had to downsize during the recession.', 'C1', 'business'),
  ('overhead', 'gastos generales', 'Working from home helped reduce their overhead.', 'C1', 'business'),
  ('incentive', 'incentivo', 'Bonuses are a strong incentive to work harder.', 'C1', 'business'),
  ('viable', 'viable', 'Solar power is now a viable alternative to coal.', 'C1', 'business'),
  ('empirical', 'empírico', 'The claim is not supported by empirical data.', 'C1', 'academic'),
  ('underlying', 'subyacente', 'We must address the underlying causes of the crisis.', 'C1', 'academic'),
  ('correlation', 'correlación', 'There is a clear correlation between diet and health.', 'C1', 'academic'),
  ('paradigm', 'paradigma', 'The discovery led to a new paradigm in physics.', 'C1', 'academic'),
  ('inherent', 'inherente', 'There are risks inherent in any investment.', 'C1', 'academic'),
  ('cut corners', 'hacer las cosas a medias', 'Never cut corners when it comes to safety.', 'C1', 'idiom'),
  ('the tip of the iceberg', 'la punta del iceberg', 'These complaints are just the tip of the iceberg.', 'C1', 'idiom'),
  ('on the fence', 'indeciso', 'I am still on the fence about which offer to accept.', 'C1', 'idiom'),
  ('jump on the bandwagon', 'subirse al carro', 'Many brands jumped on the bandwagon once the trend took off.', 'C1', 'idiom'),
  ('a grey area', 'una zona gris, ambigua', 'The law on this topic remains a grey area.', 'C1', 'idiom')
ON CONFLICT DO NOTHING;

-- Meter todo el banco nuevo en la cola de repaso SRS.
INSERT INTO user_words (word_id)
SELECT w.id FROM words w
WHERE NOT EXISTS (SELECT 1 FROM user_words uw WHERE uw.word_id = w.id);

SELECT COUNT(*) AS palabras_totales FROM words;
