// TutorIngles — lib/guia-sonidos.js
// Cómo se lee cada letra de la pronunciación figurada.
//
// Por qué existe este fichero: la figurada quitó el AFI, que era un alfabeto
// que había que aprender aparte. Pero metió dos símbolos nuevos —ə y æ— y unas
// cuantas convenciones. Si no están explicadas donde se ven, se repite el mismo
// problema en pequeño.
//
// El orden es por lo que más se nota al hablar, no por el orden del alfabeto:
// arriba lo que hay que aprender sí o sí, abajo lo que ya sale gratis en
// castellano.

const GUIA = [
  // ── LO PRIMERO: el sonido más frecuente del inglés ──
  {
    simbolo: 'ə',
    clase: 'floja',
    nombre: 'la e al revés',
    grupo: 'vocales',
    prioridad: 1,
    como: 'El sonido de no hacer nada con la boca. Entreabierta, lengua plana, sin fuerza. Ni a, ni e: lo de en medio.',
    truco: 'Es la vocal de dudar: "eeeh…". O la e de "padre" cuando hablas rápido y no la cuidas.',
    ejemplos: [['better', 'BE-tə'], ['colour', 'KA-lə'], ['the', 'də'], ['a bit', 'ə BIT']],
    error: 'Decir la vocal que está escrita. "colour" no es "co-LOR": es KA-lə, la segunda vocal se desploma.',
    dato: 'Es el sonido más repetido del inglés: sale en 65.213 de las 147.488 palabras del diccionario. Nunca va en mayúscula, porque nunca lleva el golpe de voz.',
  },
  {
    simbolo: 'ëë',
    clase: 'larga',
    nombre: 'la e floja y larga',
    grupo: 'vocales',
    prioridad: 2,
    como: 'Una e estirada dicha sin mover nada: la boca a medio abrir, la lengua quieta y los labios sin estirar. Es la ə, pero larga y con fuerza.',
    truco: 'Di "eeeh…" de dudar y alárgalo. No pongas boca de sonrisa, que es lo que la convierte en e española.',
    ejemplos: [['work', 'UËËK'], ['shirt', 'SHËËT'], ['first', 'FËËST'], ['person', 'PËË-sən']],
    error: 'Decir la e de "mesa" (UEEK suena a "week") o meter la r que está escrita: en británico "work" no lleva r.',
    dato: 'Aparece en casi todas las palabras con er/ir/ur/or átona escrita: work, girl, turn, world, learn.',
  },
  {
    simbolo: 'æ',
    clase: 'ajeno',
    nombre: 'la a con e pegada',
    grupo: 'vocales',
    prioridad: 3,
    como: 'A medio camino entre nuestra a y nuestra e, con la boca bien abierta y la mandíbula baja.',
    truco: 'Di "a" y, sin parar el sonido, abre más la boca como cuando el médico te mira la garganta.',
    ejemplos: [['cat', 'KÆT'], ['bad', 'BÆD'], ['black', 'BLÆK'], ['bag', 'BÆG']],
    error: 'Cambiarla por una a española (KAT) o por una e (KET). Con la a, "bad" suena a "bud"; con la e, a "bed".',
  },
  {
    simbolo: 'ii uu aa oo',
    clase: 'larga',
    nombre: 'vocal doblada',
    grupo: 'vocales',
    prioridad: 4,
    como: 'La misma vocal, pero estirada de verdad: dura casi el doble. No es adorno, distingue palabras.',
    truco: 'Cuenta dos tiempos mentalmente mientras la dices.',
    ejemplos: [['sheep', 'SHIIP'], ['food', 'FUUD'], ['car', 'KAA'], ['law', 'LOO']],
    error: 'Acortarla. "sheep" dicho corto es "ship", que es barco en vez de oveja.',
  },
  {
    simbolo: 'i u',
    clase: 'floja',
    nombre: 'vocal corta y floja',
    grupo: 'vocales',
    prioridad: 5,
    como: 'Corta y sin tensión. La i se cae hacia la e, y la u hacia la o.',
    truco: 'No pongas los labios en su sitio del todo. Es una vocal perezosa.',
    ejemplos: [['ship', 'SHIP'], ['bit', 'BIT'], ['book', 'BUK'], ['full', 'FUL']],
    error: 'Decirla tensa como la i española. "ship" con la i española acaba sonando a "sheep".',
  },

  // ── CONSONANTES QUE NO EXISTEN EN ESPAÑOL ──
  {
    simbolo: 'v',
    clase: 'ajeno',
    nombre: 've de dientes',
    grupo: 'consonantes',
    prioridad: 6,
    como: 'El labio de abajo toca los dientes de arriba y el aire pasa rozando. Los labios NO se juntan.',
    truco: 'Empieza a decir una f y añade voz sin mover nada.',
    ejemplos: [['very', 'VE-ri'], ['vote', 'VOUT'], ['have', 'HÆV']],
    error: 'Decirla como b. En español "vaca" y "baca" suenan igual; en inglés "berry" y "very" no.',
  },
  {
    simbolo: 's',
    clase: 'ajeno',
    nombre: 'ese que zumba',
    grupo: 'consonantes',
    prioridad: 7,
    como: 'Una s con la garganta vibrando. En la figurada va en color: si está marcada, zumba.',
    truco: 'Pon la mano en el cuello. Con la s normal no notas nada; con esta, cosquilleo.',
    ejemplos: [['is', 'is'], ['these', 'DIIS'], ['prize', 'PRAIS'], ['shoes', 'SHUUS']],
    error: 'Ensordecerla, sobre todo en los plurales. Es lo que más marca el acento en un mostrador: "sizes", "shoes", "prices" salen sin zumbido.',
  },
  {
    simbolo: 'r',
    clase: 'ajeno',
    nombre: 'erre que no vibra',
    grupo: 'consonantes',
    prioridad: 8,
    como: 'La lengua se acerca al paladar pero no llega a tocar. No golpea ni vibra nunca.',
    truco: 'Empieza a decir una r española y párala a mitad de camino. Redondea un poco los labios.',
    ejemplos: [['red', 'RED'], ['right', 'RAIT'], ['really', 'RI-ə-li']],
    error: 'Vibrarla. Una rr española en "red" se oye a un kilómetro.',
    dato: 'Y en británico, la r del final no se dice: "car" es KAA, no "car".',
  },
  {
    simbolo: 'sh',
    clase: 'ajeno',
    nombre: 'la de mandar callar',
    grupo: 'consonantes',
    prioridad: 9,
    como: 'Aire continuo con la lengua cerca del paladar. Sin golpe al empezar.',
    truco: 'Es literalmente el "shhh" de pedir silencio.',
    ejemplos: [['shop', 'SHOP'], ['size', 'SAIS'], ['cash', 'KÆSH']],
    error: 'Cambiarla por ch. "shop" dicho CHOP es otra palabra (cortar).',
  },
  {
    simbolo: 'dj',
    clase: 'ajeno',
    nombre: 'la jota inglesa',
    grupo: 'consonantes',
    prioridad: 10,
    como: 'Una ch con la garganta vibrando.',
    truco: 'Di "ch" y, sin soltar la lengua, mete voz. Es la j de John y la g de "change".',
    ejemplos: [['change', 'CHEINDJ'], ['jacket', 'DJÆ-kit'], ['just', 'DJAST']],
    error: 'Cambiarla por y ("yet" en lugar de "jet") o dejarla en ch al final de palabra.',
  },
  {
    simbolo: 'ng',
    clase: 'ajeno',
    nombre: 'la ene del fondo',
    grupo: 'consonantes',
    prioridad: 11,
    como: 'La lengua toca el paladar del fondo y la punta no toca nada. Sin g detrás.',
    truco: 'Di "tengo" y párate justo antes de la g. Eso que queda es el sonido.',
    ejemplos: [['thing', 'ZING'], ['looking', 'LU-king'], ['shopping', 'SHO-ping']],
    error: 'Rematar con una g dura ("thin-GO") o comerse el sonido y decir "thin".',
  },
  {
    simbolo: 'h',
    clase: 'ajeno',
    nombre: 'la h que SÍ suena',
    grupo: 'consonantes',
    prioridad: 12,
    como: 'Solo aire, un soplo suave. La garganta no raspa: no la aprietes.',
    truco: 'El soplo con el que empañas un cristal antes de limpiarlo.',
    ejemplos: [['hello', 'hə-LOU'], ['hand', 'HÆND'], ['have', 'HÆV'], ['who', 'HUU']],
    error: 'Los dos extremos: no decirla (en español la h es muda) o decirla como la j de "jamón", que suena a carraspeo. Va en color justo para avisar de que ahí hay que soplar.',
    dato: 'Antes esta letra se escribía "j" en la figurada, y todo el mundo la raspaba. Ahora se escribe h, pero marcada: si está en color, se dice.',
  },
  {
    simbolo: 'u',
    clase: 'ajeno',
    nombre: 'la u de "hueso"',
    grupo: 'consonantes',
    prioridad: 13,
    como: 'Labios redondeados y hacia fuera, y de ahí se pasa a la vocal siguiente.',
    truco: 'Es la u de "hueso" o "huevo".',
    ejemplos: [['what', 'UOT'], ['one', 'UON'], ['would', 'uud']],
    error: 'Meterle una g delante, como en "guasap". No es GUOT, es UOT.',
  },
  {
    simbolo: 'zh',
    clase: 'ajeno',
    nombre: 'la sh con voz',
    grupo: 'consonantes',
    prioridad: 14,
    como: 'Como la sh pero con la garganta vibrando. Sale poco.',
    truco: 'Es la j francesa de "bonjour".',
    ejemplos: [['usually', 'YUU-zhu-ə-li'], ['measure', 'ME-zhə']],
  },

  // ── LO QUE YA SABES HACER: la ventaja del castellano ──
  {
    simbolo: 'z',
    clase: 'ok',
    nombre: 'la zeta de "zapato"',
    grupo: 'gratis',
    prioridad: 15,
    como: 'Exactamente nuestra z, con la punta de la lengua entre los dientes.',
    truco: 'No hay truco: ya la haces. Es la th de "think".',
    ejemplos: [['think', 'ZINGK'], ['three', 'ZRII'], ['healthy', 'HEL-zi']],
    dato: 'Un latinoamericano tiene que aprender este sonido desde cero. Tú no.',
  },
  {
    simbolo: 'd',
    clase: 'ok',
    nombre: 'la de de "cada"',
    grupo: 'gratis',
    prioridad: 16,
    como: 'La d suave de entre vocales, con la lengua asomando un poco. Es la th de "this".',
    truco: 'Di "cada" o "nada" y fíjate en esa d floja: esa misma.',
    ejemplos: [['the', 'də'], ['this', 'DIS'], ['with', 'uid']],
    dato: 'También sale gratis en castellano. Lo tienes de serie.',
  },
  {
    simbolo: 'ch y',
    clase: 'ok',
    nombre: 'suenan como en español',
    grupo: 'gratis',
    prioridad: 17,
    como: 'La ch de "coche" y la y de "ya". Sin cambios.',
    ejemplos: [['cheap', 'CHIIP'], ['yes', 'YES'], ['watch', 'UOCH']],
  },
];

// Marcas de escritura, que no son sonidos sino cómo está escrita la figurada.
const MARCAS = [
  { simbolo: 'MAYÚSCULAS', nombre: 'el golpe de voz',
    como: 'La sílaba en mayúsculas es la que suena más fuerte y más larga. En inglés solo hay una por palabra y equivocarla cambia el ritmo entero.',
    ejemplos: [['receipt', 'ri-SIIT'], ['fitting', 'FI-ting']] },
  { simbolo: 'minúsculas', nombre: 'palabra que se come',
    como: 'Las palabras escritas pequeñas y grises van sin fuerza: son las de relleno (the, of, to, you). El inglés se apoya en las que tienen contenido y pasa de puntillas por el resto.',
    ejemplos: [['the black one', 'də BLÆK UON'], ['a bit small', 'ə BIT SMOOL']] },
  { simbolo: '·', nombre: 'separa sílabas',
    como: 'Solo sirve para leer más fácil: no se pronuncia ni se hace pausa.',
    ejemplos: [['better', 'BE·tə']] },
];

module.exports = { GUIA, MARCAS };
